name: wruJoin
version: '${version}'
main: dev.naw0ke.wrujoin.WruJoinPlugin
api-version: '1.21'
authors: [ Naw0ke ]
description: A high-quality join message plugin.
website: https://stmstudios.net
folia-supported: true
dependencies:
  server:
    SuperVanish:
      load: BEFORE
      required: false